/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ButtonList: typeof import('./src/components/ButtonList.vue')['default']
    CalendarMonth: typeof import('./src/components/Calendar/CalendarMonth.vue')['default']
    CalendarYear: typeof import('./src/components/Calendar/CalendarYear.vue')['default']
    CodeCard: typeof import('./src/components/CodeCard.vue')['default']
    EchartsCard: typeof import('./src/components/EchartsCard.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElLink: typeof import('element-plus/es')['ElLink']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    IconSvg: typeof import('./src/components/IconSvg.vue')['default']
    JsonView: typeof import('./src/components/JsonView.vue')['default']
    MarkdownCard: typeof import('./src/components/MarkdownCard.vue')['default']
    MonthCalendar: typeof import('./src/components/MonthCalendar.vue')['default']
    NoticeBar: typeof import('./src/components/NoticeBar.vue')['default']
    OfficeFileReader: typeof import('./src/components/OfficeFileReader.vue')['default']
    ResizeCard: typeof import('./src/components/ResizeCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SimpleSwiper: typeof import('./src/components/SimpleSwiper.vue')['default']
    TabsScroll: typeof import('./src/components/TabsScroll.vue')['default']
    TerminalCard: typeof import('./src/components/TerminalCard.vue')['default']
    TerminalCardCopy: typeof import('./src/components/TerminalCardCopy.vue')['default']
  }
}
